# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
# %run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
import numpy as np
a = np.__version__
b = np.show_config
a
b

<function numpy.__config__.show(mode='stdout')>

#### 3. Create a null vector of size 10 (★☆☆)

In [7]:
import	numpy as np
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [9]:
import numpy as np
a = np.zeros(10)
a.nbytes

80

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [3]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retai

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [9]:
a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [14]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [22]:
a =np.array([1,2,3,4,5,6])
a[::-1]

array([6, 5, 4, 3, 2, 1])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [28]:
print(np.arange(9).reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [29]:
a = [1,2,0,0,4,0]
for i in range(len(a)):
    if a[i] != 0:
        print(i)

0
1
4


#### 11. Create a 3x3 identity matrix (★☆☆)

In [32]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [33]:
np.arange(27).reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [44]:
a = np.arange(100).reshape(10,10)
print(a)
print(a.max())
print(a.min())

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
99
0


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [49]:
a = np.arange(1,31)
print(a)
print(a.mean())

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]
15.5


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [51]:
a = np.ones((7,7))
a[1:-1,1:-1] = 0
a

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [75]:
a = np.ones((8,8),dtype=int)
b = np.pad(a,pad_width=1,mode='constant',constant_values=0)
print(b)

[[0 0 0 0 0 0 0 0 0 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 0 0 0 0 0 0 0 0 0]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [83]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [89]:
a = np.zeros((5,5))
np.fill_diagonal(a,[1,2,2,3,4])
print(a)

[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 2. 0. 0.]
 [0. 0. 0. 3. 0.]
 [0. 0. 0. 0. 4.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [14]:
ch_b = np.zeros((8,8),dtype=int)
ch_b[1::2 , ::2] = 1
ch_b[::2 , 1::2] = 1
print(ch_b)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [100]:
a = np.unravel_index(99,(6,7,8))
a

(np.int64(1), np.int64(5), np.int64(3))

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [102]:
a = np.array([[1, 2], [3, 4]])
print(np.tile(a, (8, 8)))

[[1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2]
 [3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4]
 [1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2]
 [3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4]
 [1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2]
 [3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4]
 [1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2]
 [3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4]
 [1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2]
 [3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4]
 [1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2]
 [3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4]
 [1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2]
 [3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4]
 [1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2]
 [3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [110]:
a = np.arange(25).reshape(5,5)
a_min = a.min()
a_max = a.max()
normalized_a = (a-a_min)/(a_max-a_min)
normalized_a

array([[0.        , 0.04166667, 0.08333333, 0.125     , 0.16666667],
       [0.20833333, 0.25      , 0.29166667, 0.33333333, 0.375     ],
       [0.41666667, 0.45833333, 0.5       , 0.54166667, 0.58333333],
       [0.625     , 0.66666667, 0.70833333, 0.75      , 0.79166667],
       [0.83333333, 0.875     , 0.91666667, 0.95833333, 1.        ]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [17]:
rgba_dtype = np.dtype([
    ('red' , np.uint8),
    ('green' , np.uint8),
    ('blue' , np.uint8),
    ('alpha' , np.uint8)
])
color = np.array((255, 128, 0, 255), dtype=rgba_dtype)
print(color)
print('r:',color['red'])
print('g:',color['green'])
print('b:',color['blue'])
print('a:',color['alpha'])

(255, 128, 0, 255)
r: 255
g: 128
b: 0
a: 255


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [111]:
a = np.arange(15).reshape(5,3)
b = np.arange(6).reshape(3,2)
a@b

array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [125]:
a = np.arange(1,12)
a[(a>3)&(a<8)]*=-1
a

array([ 1,  2,  3, -4, -5, -6, -7,  8,  9, 10, 11])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [127]:
print(sum(range(5),-1))

9


In [128]:
from numpy import *
print(sum(range(5),-1))

10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [144]:
Z = np.arange(7)
Z**Z 
print('Legal')
2<<Z>>2
print('Legal')
Z<-Z
print('Legal')
1j*Z
print('Legal')
Z/1/1
print('legal')
#Z<Z>
print('Not Legal')

Legal
Legal
Legal
Legal
legal
Not Legal


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [150]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


C:\Users\Tech Pool\AppData\Local\Temp\ipykernel_2576\3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\Tech Pool\AppData\Local\Temp\ipykernel_2576\3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\Tech Pool\AppData\Local\Temp\ipykernel_2576\3912170336.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [158]:
a = np.array([0.5,2.6,3.4,7.5,4.9,8.7])
b = np.where(a>0,np.ceil(a),np.floor(a))
print(b)

[1. 3. 4. 8. 5. 9.]


#### 30. How to find common values between two arrays? (★☆☆)

In [164]:
a = np.array([1,2,3,4,5,6,7,8])
b = np.array([4,6,8,10,11,16])
c1 = a[np.isin(a,b)]
print(c1)

[4 6 8]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [165]:
import warnings
warnings.filterwarnings('ignore',module='numpy')

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [167]:
np.sqrt(-1) == np.emath.sqrt(-1)
#Not-True, because np.sqrt(-1) gives runtime warning and np.emath.sqrt(-1) gives imaginamr number.

C:\Users\Tech Pool\AppData\Local\Temp\ipykernel_2576\492479729.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


np.False_

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [172]:
from datetime import date,timedelta
today = date.today()
yesterday = today - timedelta(days=1)
tomorrow = today + timedelta(days=1)
print(today)
print(yesterday)
print(tomorrow)

2025-05-30
2025-05-29
2025-05-31


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [174]:
from datetime import date,timedelta
start_date = date(2016,7,1)
end_date = date(2016,7,31)
dates_in_july = [start_date + timedelta(days=i) for i in range((end_date - start_date).days + 1)]
for d in dates_in_july:
    print(d)

2016-07-01
2016-07-02
2016-07-03
2016-07-04
2016-07-05
2016-07-06
2016-07-07
2016-07-08
2016-07-09
2016-07-10
2016-07-11
2016-07-12
2016-07-13
2016-07-14
2016-07-15
2016-07-16
2016-07-17
2016-07-18
2016-07-19
2016-07-20
2016-07-21
2016-07-22
2016-07-23
2016-07-24
2016-07-25
2016-07-26
2016-07-27
2016-07-28
2016-07-29
2016-07-30
2016-07-31


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
#To fully do in-place without copies, you need to preserve original A before modifying it.

#Then use in-place operators +=, *=

#Or use out parameter to avoid temporaries.

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [182]:
a = [4.67,7.23,9.54,3.6,0.3,4.7]
# method-1:
print(np.floor(a).astype(int))
# method-2:
print(np.trunc(a).astype(int))
# method-3:
print(np.array(a).astype(int))
# method-4:
print(np.fix(a).astype(int))

[4 7 9 3 0 4]
[4 7 9 3 0 4]
[4 7 9 3 0 4]
[4 7 9 3 0 4]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [183]:
print(np.tile(np.arange(5),(5,1)))

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [184]:
def generate_integers():
    for i in range(10):
        yield i

In [187]:
import numpy as np
gen = generate_integers()             
arr = np.fromiter(gen, dtype=int)     
print(arr)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [188]:
np.linspace(0,1,12,endpoint=True)[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [193]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [197]:
a = np.array([1,2,3,4,5])
b = sum(a)
print(b)
# sum() is faster then np.sum()

15


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [26]:
a = np.random.rand(12)
b = np.random.rand(12)
if np.array_equal(a,b):
    print('True')
else: 
    print('False')

False


#### 43. Make an array immutable (read-only) (★★☆)

In [201]:
a = np.array([1,2,3,4,5,6])
a.flags.writeable = False
a
a[0] = 10

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [209]:
cart = np.random.rand(10,2)*10
print('Cartision_matrix:')
print(cart)
x = cart[:,0]
y = cart[:,1]
r = sqrt(x**2+y**2)
theta = arctan2(y,x)
polar = np.column_stack((r,theta))
print()
print('Polar_matrix:')
print(polar)

Cartision_matrix:
[[2.47363674 0.94630508]
 [9.1632223  1.94786635]
 [9.94792473 2.97045501]
 [0.50363517 1.23117625]
 [0.18831344 4.52619187]
 [2.97852404 4.18972337]
 [6.28428311 7.93981016]
 [2.45807229 3.46859624]
 [1.94217695 9.44187701]
 [6.16802263 1.51859787]]

Polar_matrix:
[[ 2.64846597  0.36537877]
 [ 9.3679681   0.20945656]
 [10.38194633  0.29017233]
 [ 1.33020425  1.18249698]
 [ 4.53010759  1.52921504]
 [ 5.14056295  0.95278445]
 [10.12584809  0.90126578]
 [ 4.25126796  0.95427866]
 [ 9.63955874  1.3679278 ]
 [ 6.35221557  0.2414037 ]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [217]:
a = np.random.rand(1,10)
print(a)
print()
a1 = max(a)
print(a1)
print()
a[a==a1]=0
print(a)

[[0.86110786 0.06625344 0.60897383 0.10319697 0.36935207 0.78338492
  0.01442995 0.32990826 0.19633855 0.88194301]]

0.8819430103808038

[[0.86110786 0.06625344 0.60897383 0.10319697 0.36935207 0.78338492
  0.01442995 0.32990826 0.19633855 0.        ]]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [19]:
n = 5
x = np.linspace(1,0,n)
y = np.linspace(1,0,n)
xx,yy = np.meshgrid(x,y)
xx_flat = xx.ravel()
yy_flat = yy.ravel()
point_dtype = np.dtype([('x',np.float64),('y',np.float64)])
points = np.zeros(xx_flat.shape[0], dtype=point_dtype)
points['x'] = xx_flat
points['y'] = yy_flat
print(points)

[(1.  , 1.  ) (0.75, 1.  ) (0.5 , 1.  ) (0.25, 1.  ) (0.  , 1.  )
 (1.  , 0.75) (0.75, 0.75) (0.5 , 0.75) (0.25, 0.75) (0.  , 0.75)
 (1.  , 0.5 ) (0.75, 0.5 ) (0.5 , 0.5 ) (0.25, 0.5 ) (0.  , 0.5 )
 (1.  , 0.25) (0.75, 0.25) (0.5 , 0.25) (0.25, 0.25) (0.  , 0.25)
 (1.  , 0.  ) (0.75, 0.  ) (0.5 , 0.  ) (0.25, 0.  ) (0.  , 0.  )]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [219]:
x = random.rand(1,12)
y = random.rand(1,12)
for xi in x:
    for yi in y:
        Cij = np.array([1/(xi-yi)])
        print(Cij)

[[-29.0181919    2.93598357 -14.74586452   1.68935783   1.13510508
   -6.40539721 -55.54554879  -1.06756749   4.70266133  24.11527539
    5.97734938   2.13061358]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [18]:
import numpy as np
for dtype in [np.int8, np.int16, np.int32, np.int64,
              np.uint8, np.uint16, np.uint32, np.uint64]:
    info = np.iinfo(dtype)
    print(f"{dtype.__name__}: min = {info.min}, max = {info.max}")
print("\n")
for dtype in [np.float16, np.float32, np.float64]:
    info = np.finfo(dtype)
    print(f"{dtype.__name__}: min = {info.min}, max = {info.max}")

int8: min = -128, max = 127
int16: min = -32768, max = 32767
int32: min = -2147483648, max = 2147483647
int64: min = -9223372036854775808, max = 9223372036854775807
uint8: min = 0, max = 255
uint16: min = 0, max = 65535
uint32: min = 0, max = 4294967295
uint64: min = 0, max = 18446744073709551615


float16: min = -65504.0, max = 65504.0
float32: min = -3.4028234663852886e+38, max = 3.4028234663852886e+38
float64: min = -1.7976931348623157e+308, max = 1.7976931348623157e+308


#### 49. How to print all the values of an array? (★★☆)

In [221]:
import numpy as np

np.set_printoptions(threshold=np.inf)  # Disable summarization
arr = np.arange(100)  # Example array
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [23]:
vector = np.array([15,17,18,21,27,30,33])
n = 19
index = np.abs(n - vector).argmin()
closest_value = vector[index]
print(closest_value)

18


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [28]:
dtype = np.dtype([
    ('position', [('x', np.float32), ('y', np.float32)]),
    ('color',    [('r', np.uint8), ('g', np.uint8), ('b', np.uint8)])
])
data = np.array([
    ((0.5, 0.2), (255, 0, 0)),     
    ((0.1, 0.9), (0, 255, 0)),     
    ((0.8, 0.3), (0, 0, 255))      
], dtype=dtype)
print(data)
print()
print(data[0]['position'])
print(data[0]['color'])

[((0.5, 0.2), (255,   0,   0)) ((0.1, 0.9), (  0, 255,   0))
 ((0.8, 0.3), (  0,   0, 255))]

(0.5, 0.2)
(255, 0, 0)


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [39]:
a = np.random.rand(100,2)
diff = a[:,np.newaxis ,:] - a[np.newaxis ,:,:]
dist = np.linalg.norm(diff,axis=2)
print(dist)

[[0.         0.57048538 0.73029224 ... 0.39300424 0.42146943 0.52875096]
 [0.57048538 0.         0.74301512 ... 0.59672153 0.415919   0.61968166]
 [0.73029224 0.74301512 0.         ... 0.34127803 0.37309783 0.20154457]
 ...
 [0.39300424 0.59672153 0.34127803 ... 0.         0.19431554 0.14252539]
 [0.42146943 0.415919   0.37309783 ... 0.19431554 0.         0.20868744]
 [0.52875096 0.61968166 0.20154457 ... 0.14252539 0.20868744 0.        ]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [44]:
a = np.array([4.6,3.8,2.0,9,5],dtype = np.float32)
a = a.astype(np.int32)
print(a)

[4 3 2 9 5]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [61]:
a = np.array([[1,2,3],
             [3,4,5],
             [5,6,7]])
for i,v in np.ndenumerate(a):
    print(f"Index {i}:{v}")    #Equivalent of enumerate is ndenumerate

Index (0, 0):1
Index (0, 1):2
Index (0, 2):3
Index (1, 0):3
Index (1, 1):4
Index (1, 2):5
Index (2, 0):5
Index (2, 1):6
Index (2, 2):7


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [53]:
x = np.linspace(-1,1,10)
y = np.linspace(-1,1,10)
x,y = np.meshgrid(x,y)
gause = np.exp(-(x**2 + y**2))
print(gause)

[[0.13533528 0.20090196 0.27018673 0.32919299 0.36336564 0.36336564
  0.32919299 0.27018673 0.20090196 0.13533528]
 [0.20090196 0.2982341  0.40108566 0.48867903 0.53940751 0.53940751
  0.48867903 0.40108566 0.2982341  0.20090196]
 [0.27018673 0.40108566 0.53940751 0.65720907 0.72543221 0.72543221
  0.65720907 0.53940751 0.40108566 0.27018673]
 [0.32919299 0.48867903 0.65720907 0.8007374  0.88385983 0.88385983
  0.8007374  0.65720907 0.48867903 0.32919299]
 [0.36336564 0.53940751 0.72543221 0.88385983 0.97561098 0.97561098
  0.88385983 0.72543221 0.53940751 0.36336564]
 [0.36336564 0.53940751 0.72543221 0.88385983 0.97561098 0.97561098
  0.88385983 0.72543221 0.53940751 0.36336564]
 [0.32919299 0.48867903 0.65720907 0.8007374  0.88385983 0.88385983
  0.8007374  0.65720907 0.48867903 0.32919299]
 [0.27018673 0.40108566 0.53940751 0.65720907 0.72543221 0.72543221
  0.65720907 0.53940751 0.40108566 0.27018673]
 [0.20090196 0.2982341  0.40108566 0.48867903 0.53940751 0.53940751
  0.48867903

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [76]:
a = (6,6)
arr = np.zeros(a,dtype=int)
p = 4
idx = np.random.choice(arr.size,p)
arr.flat[idx] = 2
print(arr)

[[0 0 0 0 0 0]
 [0 0 0 0 0 2]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 2 0 2 0]
 [0 0 0 2 0 0]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [85]:
a = np.array([[1,2,3],
             [3,4,5],
             [5,6,7]])
print(a-np.mean(a))

[[-3. -2. -1.]
 [-1.  0.  1.]
 [ 1.  2.  3.]]


#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [50]:
a = np.array([[1,2,0],
             [5,7,0],
             [4,8,0]])
b = np.all(a == 0,axis=0)
print(b)

[False False  True]


#### 61. Find the nearest value from a given value in an array (★★☆)

In [52]:
a = np.array([12,14,15,18,23,26,31])
n = 20
index = np.abs(n - a).argmin()
print(a[index])

18


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [103]:
a = np.random.randint(0,10, size=(1,3))
b = np.random.randint(11,20,size=(3,1))
for i in range(len(a)):
    for j in range(len(b)):
        print(a[i]+b[j])

[13 14 20]
[18 19 25]
[13 14 20]


#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)