In [42]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

In [69]:
img = cv2.imread(r"C:\Users\Tech Pool\Downloads\directories\img_1.jpg")

print(img)

[[[13 19 24]
  [13 19 24]
  [13 19 24]
  ...
  [13 19 24]
  [13 19 24]
  [13 19 24]]

 [[13 19 24]
  [13 19 24]
  [13 19 24]
  ...
  [13 19 24]
  [13 19 24]
  [13 19 24]]

 [[13 19 24]
  [13 19 24]
  [12 18 23]
  ...
  [12 18 23]
  [13 19 24]
  [13 19 24]]

 ...

 [[22 33 37]
  [31 42 46]
  [37 48 52]
  ...
  [14 12 11]
  [13 11 10]
  [14 12 11]]

 [[22 33 37]
  [31 42 46]
  [37 48 52]
  ...
  [18 16 15]
  [15 13 12]
  [12 10  9]]

 [[22 33 37]
  [31 42 46]
  [37 48 52]
  ...
  [23 21 20]
  [17 15 14]
  [11  9  8]]]


In [70]:
cv2.imshow('Displayed Image', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [71]:
hsv = cv2.cvtColor(img,cv2.COLOR_BGR2HSV)
cv2.imshow('HSV_img',hsv)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [74]:
red_lower1 = np.array([0,100,100],np.uint8)
red_upper1 = np.array([10,255,255],np.uint8)

In [75]:
red_lower2 = np.array([160,100,100],np.uint8)
red_upper2 = np.array([180,255,255],np.uint8)

In [76]:
r_m1 = cv2.inRange(hsv,red_lower1,red_upper1)
r_m2 = cv2.inRange(hsv,red_lower2,red_upper2)

In [78]:
r_mask = np.bitwise_or(r_m1,r_m2)
cv2.imshow('mask',r_mask)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [83]:
img[r_mask>0] = (255,255,255)
cv2.imshow('change_mask',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [85]:
cv2.imwrite("image.jpg",img)

True